import React, { useState, useEffect } from 'react'
import { Calendar, momentLocalizer } from 'react-big-calendar'
import moment from 'moment'
import 'react-big-calendar/lib/css/react-big-calendar.css'

const localizer = momentLocalizer(moment)

export default function Dashboard() {
  const [isInGroup, setIsInGroup] = useState(false)
  const [groupCode, setGroupCode] = useState('')
  const [events, setEvents] = useState([])
  const [newEvent, setNewEvent] = useState({ title: '', start: '', end: '' })
  const [showAlert, setShowAlert] = useState(false)
  const [generatedCode, setGeneratedCode] = useState('')

  useEffect(() => {
    // Simulating API call to check if user is in a group
    setTimeout(() => setIsInGroup(Math.random() > 0.5), 1000)
  }, [])

  const handleJoinGroup = () => {
    console.log('Joining group with code:', groupCode)
    setIsInGroup(true)
  }

  const handleCreateGroup = () => {
    console.log('Creating group')
    setGeneratedCode('ABC123') // This should be generated by the API
    setShowAlert(true)
    setTimeout(() => {
      setShowAlert(false)
      setIsInGroup(true)
    }, 3000)
  }

  const handleAddEvent = () => {
    if (newEvent.title && newEvent.start && newEvent.end) {
      setEvents([...events, {
        ...newEvent,
        start: new Date(newEvent.start),
        end: new Date(newEvent.end)
      }])
      setNewEvent({ title: '', start: '', end: '' })
    }
  }

  if (isInGroup) {
    return (
      <div className="space-y-6">
        <div className="bg-purple-200 p-4 rounded-lg">
          <h3 className="font-bold text-lg">Grupo X</h3>
          <p className="font-semibold">Lic Corina</p>
          <p>Fecha de próxima entrega</p>
          <p className="font-semibold">16/06/2024</p>
        </div>
        <div className="bg-white p-4 rounded-lg shadow">
          <h3 className="font-bold text-lg mb-2">Mi grupo de desarrollo</h3>
          <div className="flex justify-between items-center">
            <div>
              <p className="font-semibold">RedFox SRL</p>
              <p>Iteración</p>
              <p className="font-semibold">1/5</p>
            </div>
            <div>
              <p>Representante legal</p>
              <p className="font-semibold">Oliver Alandia</p>
            </div>
            <div>
              <p>Miembros</p>
              <p className="font-semibold">6</p>
            </div>
          </div>
        </div>
        <div className="bg-white shadow-lg rounded-lg overflow-hidden">
          <div className="flex justify-between items-center p-4 bg-purple-100">
            <h3 className="font-bold text-lg">Planificación</h3>
            <button className="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded" onClick={() => {}}>
              Nuevo evento
            </button>
          </div>
          <Calendar
            localizer={localizer}
            events={events}
            startAccessor="start"
            endAccessor="end"
            style={{ height: 500 }}
            views={['month', 'week', 'day']}
          />
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <div className="max-w-md mx-auto bg-white p-6 rounded-lg shadow-md">
        <h3 className="text-center font-bold text-lg mb-4">NO ESTAS INSCRITO EN UN CURSO</h3>
        <input
          type="text"
          placeholder="Ingrese el código de la clase"
          value={groupCode}
          onChange={(e) => setGroupCode(e.target.value)}
          className="w-full p-2 border rounded mb-4"
        />
        <button onClick={handleJoinGroup} className="w-full bg-purple-600 text-white p-2 rounded mb-2">Unirse a Clase</button>
        <div className="text-center my-2">
          <span className="text-sm text-gray-500">o</span>
        </div>
        <button onClick={handleCreateGroup} className="w-full bg-purple-600 text-white p-2 rounded">Crear grupo de trabajo</button>
      </div>
      {showAlert && (
        <div className="bg-green-100 border-l-4 border-green-500 text-green-700 p-4" role="alert">
          <p className="font-bold">Grupo creado exitosamente</p>
          <p>El código de su grupo es: {generatedCode}</p>
        </div>
      )}
    </div>
  )
}